"""
Copyright [2009-2017] EMBL-European Bioinformatics Institute
Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at
http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
"""

genomes = [{'assembly': 'GRCh38',
  'assembly_ucsc': 'hg38',
  'division': 'Ensembl',
  'example_location': {'chromosome': 'X', 'end': 73856333, 'start': 73819307},
  'species': 'Homo sapiens',
  'synonyms': ['human'],
  'taxid': 9606},
 {'assembly': 'GRCm38',
  'assembly_ucsc': 'mm10',
  'division': 'Ensembl',
  'example_location': {'chromosome': 1, 'end': 86352200, 'start': 86351908},
  'species': 'Mus musculus',
  'synonyms': ['mouse'],
  'taxid': 10090},
 {'assembly': 'GRCz10',
  'assembly_ucsc': 'danRer10',
  'division': 'Ensembl',
  'example_location': {'chromosome': 9, 'end': 7634210, 'start': 7633910},
  'species': 'Danio rerio',
  'synonyms': ['zebrafish'],
  'taxid': 7955},
 {'assembly': 'UMD3.1',
  'assembly_ucsc': 'bosTau6',
  'division': 'Ensembl',
  'example_location': {'chromosome': 15, 'end': 82197837, 'start': 82197673},
  'species': 'Bos taurus',
  'synonyms': ['cow'],
  'taxid': 9913},
 {'assembly': 'Rnor_6.0',
  'assembly_ucsc': 'rn6',
  'division': 'Ensembl',
  'example_location': {'chromosome': 'X', 'end': 118277850, 'start': 118277628},
  'species': 'Rattus norvegicus',
  'synonyms': ['rat'],
  'taxid': 10116},
 {'assembly': 'CHIMP2.1.4',
  'assembly_ucsc': 'panTro4',
  'division': 'Ensembl',
  'example_location': {'chromosome': 11, 'end': 78369219, 'start': 78369004},
  'species': 'Pan troglodytes',
  'synonyms': ['chimp'],
  'taxid': 9598},
 {'assembly': 'CanFam3.1',
  'assembly_ucsc': 'canFam3',
  'division': 'Ensembl',
  'example_location': {'chromosome': 19, 'end': 22007119, 'start': 22006909},
  'species': 'Canis familiaris',
  'synonyms': ['dog', 'Canis lupus familiaris'],
  'taxid': 9615},
 {'assembly': 'ASM294v2',
  'assembly_ucsc': '',
  'division': 'Ensembl Fungi',
  'example_location': {'chromosome': 'I', 'end': 544327, 'start': 540951},
  'species': 'Schizosaccharomyces pombe',
  'synonyms': ['fission yeast'],
  'taxid': 4896},
 {'assembly': 'WBcel235',
  'assembly_ucsc': '',
  'division': 'Ensembl Metazoa',
  'example_location': {'chromosome': 'III', 'end': 11467705, 'start': 11467363},
  'species': 'Caenorhabditis elegans',
  'synonyms': ['worm'],
  'taxid': 6239},
 {'assembly': 'BDGP6',
  'assembly_ucsc': 'dm6',
  'division': 'Ensembl Metazoa',
  'example_location': {'chromosome': '3R', 'end': 7475217, 'start': 7474331},
  'species': 'Drosophila melanogaster',
  'synonyms': ['fly'],
  'taxid': 7227},
 {'assembly': 'GCA_000151625.1',
  'assembly_ucsc': '',
  'division': 'Ensembl Metazoa',
  'example_location': {'chromosome': 'scaf16', 'end': 6180422, 'start': 6180018},
  'species': 'Bombyx mori',
  'synonyms': ['silkworm'],
  'taxid': 7091},
 {'assembly': 'TAIR10',
  'assembly_ucsc': '',
  'division': 'Ensembl Plants',
  'example_location': {'chromosome': 2, 'end': 18822629, 'start': 18819643},
  'species': 'Arabidopsis thaliana',
  'synonyms': [],
  'taxid': 3702},
 {'assembly': 'PPYG2',
  'assembly_ucsc': 'PPYG2',
  'division': 'Ensembl',
  'example_location': {'chromosome': '7', 'end': 155766984, 'start': 155766898},
  'species': 'Pongo abelii',
  'synonyms': ['ponabe',
               '9601',
               'pabe',
               'ppyg',
               'orang',
               'ponpyg',
               'pongo abelii',
               'ppygmaeus',
               'sumatran orangutan',
               'orang_utan',
               'bornean orangutan',
               'pongo pygmaeus',
               'pongo_pygmaeus',
               'orangutan',
               'pabelii',
               'Bornean orangutan'],
  'taxid': 9601},
 {'assembly': 'OryCun2.0',
  'assembly_ucsc': 'OryCun2.0',
  'division': 'Ensembl',
  'example_location': {'chromosome': '4', 'end': 86072164, 'start': 86072062},
  'species': 'Oryctolagus cuniculus',
  'synonyms': ['orycun',
               'oryctolagus cuniculus',
               'ocun',
               'ocuniculus',
               'rabbit',
               '9986',
               'rabbit'],
  'taxid': 9986},
 {'assembly': 'TETRAODON8',
  'assembly_ucsc': 'TETRAODON8',
  'division': 'Ensembl',
  'example_location': {'chromosome': '13', 'end': 8066682, 'start': 8066583},
  'species': 'Tetraodon nigroviridis',
  'synonyms': ['tnig',
               'fresh water pufferfish',
               '99883',
               'tetnig',
               'spotted green pufferfish',
               'tetraodon',
               'tnigroviridis',
               'tetraodon nigroviridis',
               'spotted green pufferfish'],
  'taxid': 99883},
 {'assembly': 'MEDAKA1',
  'assembly_ucsc': 'MEDAKA1',
  'division': 'Ensembl',
  'example_location': {'chromosome': '14', 'end': 1414454, 'start': 1414345},
  'species': 'Oryzias latipes',
  'synonyms': ['oryzias latipes',
               'japanese medaka',
               '8090',
               'medaka',
               'orylat',
               'olat',
               'olatipes',
               'Japanese medaka'],
  'taxid': 8090},
 {'assembly': 'OANA5',
  'assembly_ucsc': 'OANA5',
  'division': 'Ensembl',
  'example_location': {'chromosome': 'Ultra151', 'end': 2274547, 'start': 2272419},
  'species': 'Ornithorhynchus anatinus',
  'synonyms': ['oana',
               'ornithorhynchus anatinus',
               'oanatinus',
               'ornana',
               'platypus',
               '9258',
               'platypus'],
  'taxid': 9258},
 {'assembly': 'BROADO5',
  'assembly_ucsc': 'BROADO5',
  'division': 'Ensembl',
  'example_location': {'chromosome': '2', 'end': 354963431, 'start': 354949926},
  'species': 'Monodelphis domestica',
  'synonyms': ['mdom',
               'mondom',
               'mdomestica',
               'gray short-tailed opossum',
               '13616',
               'opossum',
               'monodelphis domestica',
               'gray short-tailed opossum'],
  'taxid': 13616},
 {'assembly': 'EquCab2',
  'assembly_ucsc': 'EquCab2',
  'division': 'Ensembl',
  'example_location': {'chromosome': '30', 'end': 26398856, 'start': 26398748},
  'species': 'Equus caballus',
  'synonyms': ['9796',
               'equuscaballus',
               'ecaballus',
               'horse',
               'equus caballus',
               'ecab',
               'equcab',
               'horse'],
  'taxid': 9796},
 {'assembly': 'KH',
  'assembly_ucsc': 'KH',
  'division': 'Ensembl',
  'example_location': {'chromosome': '1', 'end': 5485299, 'start': 5485219},
  'species': 'Ciona intestinalis',
  'synonyms': ['ciona',
               'cioint',
               'cintestinalis',
               'cint',
               '7719',
               'c.intestinalis',
               'sea squirt ciona intestinalis',
               'ciona intestinalis',
               'Sea squirt Ciona intestinalis'],
  'taxid': 7719},
 {'assembly': 'Sscrofa11.1',
  'assembly_ucsc': 'Sscrofa11.1',
  'division': 'Ensembl',
  'example_location': {'chromosome': '13', 'end': 22859271, 'start': 22859188},
  'species': 'Sus scrofa',
  'synonyms': ['sscrofa',
               '9823',
               'sscr',
               'pigs',
               'swine',
               'sus scrofa',
               'pig',
               'wild boar',
               'pig'],
  'taxid': 9823},
 {'assembly': 'C_jacchus3.2.1',
  'assembly_ucsc': 'C_jacchus3.2.1',
  'division': 'Ensembl',
  'example_location': {'chromosome': '16', 'end': 69523910, 'start': 69523614},
  'species': 'Callithrix jacchus',
  'synonyms': ['callithrix jacchus',
               'cj321',
               'white-tufted-ear marmoset',
               'caljac',
               'cjacchus',
               'cjacchus321',
               'marmoset',
               '9483',
               'cjac',
               'white-tufted-ear marmoset'],
  'taxid': 9483},
 {'assembly': 'Gallus_gallus-5.0',
  'assembly_ucsc': 'Gallus_gallus-5.0',
  'division': 'Ensembl',
  'example_location': {'chromosome': '1', 'end': 32041012, 'start': 32039726},
  'species': 'Gallus gallus',
  'synonyms': ['galgal',
               'ggallus',
               'gallus gallus',
               'chicken',
               'ggal',
               'g_gallus',
               '9031',
               'chicken'],
  'taxid': 9031},
 {'assembly': 'Mmul_8.0.1',
  'assembly_ucsc': 'Mmul_8.0.1',
  'division': 'Ensembl',
  'example_location': {'chromosome': '5', 'end': 153753466, 'start': 153753376},
  'species': 'Macaca mulatta',
  'synonyms': ['rhesus',
               'macaca mulatta',
               'macaque',
               'rhesus_monkey',
               'macmul',
               '9544',
               'mmulatta',
               'rhesus monkey',
               'mmul',
               'rhesus monkey'],
  'taxid': 9544},
 {'assembly': 'taeGut3.2.4',
  'assembly_ucsc': 'taeGut3.2.4',
  'division': 'Ensembl',
  'example_location': {'chromosome': 'Un', 'end': 12645526, 'start': 12645442},
  'species': 'Taeniopygia guttata',
  'synonyms': ['tguttata',
               'zebra finch',
               'taeniopygia guttata',
               'taegut',
               'tgut',
               'taeniopygiaguttata',
               'taeniopygia',
               'finch',
               'zebrafinch',
               '59729',
               'zebra finch'],
  'taxid': 59729},
 {'assembly': 'PapAnu2.0',
  'assembly_ucsc': 'PapAnu2.0',
  'division': 'Ensembl',
  'example_location': {'chromosome': '1', 'end': 195028994, 'start': 195028888},
  'species': 'Papio anubis',
  'synonyms': ['papan',
               'papio hamadryas doguera',
               'papio hamadryas anubis',
               'papio cynocephalus anubis',
               'olive baboon',
               'papio anubis',
               'panubis',
               'papio doguera',
               'anubis baboon',
               'pan',
               'doguera baboon',
               '9555',
               'kenya baboon',
               'Olive baboon'],
  'taxid': 9555},
 {'assembly': 'Oar_v3.1',
  'assembly_ucsc': 'Oar_v3.1',
  'division': 'Ensembl',
  'example_location': {'chromosome': '26', 'end': 529066, 'start': 528983},
  'species': 'Ovis aries',
  'synonyms': ['ovis aries',
               'ovisaries',
               'oaries',
               'oar',
               '9940',
               'oari',
               'sheep',
               'domestic sheep',
               'oviari',
               'Domestic sheep'],
  'taxid': 9940},
 {'assembly': 'AnoCar2.0',
  'assembly_ucsc': 'AnoCar2.0',
  'division': 'Ensembl',
  'example_location': {'chromosome': '2', 'end': 121210016, 'start': 121204167},
  'species': 'Anolis carolinensis',
  'synonyms': ['anolis_lizard',
               'anocar',
               'anoliscarolinensis',
               'acarolinensis',
               'anole lizard',
               'anolis',
               '28377',
               'green anole lizard',
               'green anole',
               'anolis carolinensis',
               'acar',
               'green anole'],
  'taxid': 28377},
 {'assembly': 'UMD2',
  'assembly_ucsc': 'UMD2',
  'division': 'Ensembl',
  'example_location': {'chromosome': '30', 'end': 650869, 'start': 650792},
  'species': 'Meleagris gallopavo',
  'synonyms': ['mgal',
               'mgallopavo',
               'turkey',
               'melgal',
               'wild turkey',
               'common turkey',
               'meleagris gallopavo',
               'mga',
               '9103',
               'domestic turkey'],
  'taxid': 9103},
 {'assembly': 'ChlSab1.1',
  'assembly_ucsc': 'ChlSab1.1',
  'division': 'Ensembl',
  'example_location': {'chromosome': '20', 'end': 13225164, 'start': 13225040},
  'species': 'Chlorocebus sabaeus',
  'synonyms': ['60711',
               'vervet monkey',
               'african green monkey',
               'chlorocebus sabaeus',
               'agm',
               'chlorocebus_sabeus',
               'chlorocebus sabeus',
               'vervet-agm',
               'csab',
               'chlsab',
               'csabaeus',
               'African green monkey'],
  'taxid': 60711},
 {'assembly': 'LepOcu1',
  'assembly_ucsc': 'LepOcu1',
  'division': 'Ensembl',
  'example_location': {'chromosome': 'LG1', 'end': 41570612, 'start': 41570494},
  'species': 'Lepisosteus oculatus',
  'synonyms': ['loculatus',
               'lepoc',
               'loc',
               'lepisosteus oculatus',
               '7918',
               'spotted gar',
               'Spotted gar'],
  'taxid': 7918},
 {'assembly': 'Felis_catus_6.2',
  'assembly_ucsc': 'Felis_catus_6.2',
  'division': 'Ensembl',
  'example_location': {'chromosome': 'B3', 'end': 144419197, 'start': 144419120},
  'species': 'Felis catus',
  'synonyms': ['9685',
               'fcatus',
               'domestic cat',
               'cat',
               'felis catus',
               'fcat',
               'felcat',
               'domestic cat'],
  'taxid': 9685}]
